### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by helgi**
See https://docs.python.org/3/library/fcntl.html

### CODE REVIEW

**Comment by derpston** [comment]
Looks good to me, thank you for your contribution!

Just because I'm curious, are you able to share what you're using this module for?

**Comment by helgi** [comment]
Thanks for getting to this and merging :)

It's being used in github.com/deis/deis and github.com/deis/workflow to deal with concurrency problems Docker seems to have with it's registry.  https://github.com/deis/workflow/blob/master/rootfs/registry/dockerclient.py specifically if you want to see code, simple enough :)

Are you going to throw this up on pypi at some point soon?

**Comment by derpston** [comment]
Cool, it's nice to see another project using it.

Yup, here you go: https://pypi.python.org/pypi/simpleflock/0.0.3

**Comment by helgi** [comment]
Thanks :)

**Pull request merged**
